import React, { createContext, useContext, useState, useEffect } from 'react';
import { MOCK_DATA, BUSINESS_PROFILES, INTEGRATIONS } from '../data/mockData';
import { supabase } from '../lib/supabaseClient';

const AppContext = createContext();

export function AppProvider({ children }) {
  const [theme, setTheme] = useState('dark');
  const [isLandingPage, setIsLandingPage] = useState(true);
  const [user, setUser] = useState(null);
  const [profile, setProfile] = useState(null);
  const [profileLoading, setProfileLoading] = useState(true);
  const [currentBusinessId, setCurrentBusinessId] = useState('cafe');
  const [activeTab, setActiveTab] = useState('dashboard');
  const [businessData, setBusinessData] = useState(MOCK_DATA);
  const [integrations, setIntegrations] = useState(INTEGRATIONS);
  const [notifications, setNotifications] = useState([
    { id: 'n-1', text: 'New High Priority Lead on WhatsApp', time: '5m ago', type: 'lead', unread: true },
    { id: 'n-2', text: 'Urgent Negative Review detected on Google Maps', time: '1h ago', type: 'review', unread: true },
    { id: 'n-3', text: 'Daily summary generated by Sutra AI', time: '8:00 AM', type: 'system', unread: false }
  ]);
  const [searchQuery, setSearchQuery] = useState('');

  // Live Pipeline Monitor State
  const [pipelineLogs, setPipelineLogs] = useState([
    { id: 1, step: 'idle', status: 'ready', message: 'System listening for incoming API webhooks...', timestamp: new Date().toLocaleTimeString() }
  ]);
  const [isPipelineActive, setIsPipelineActive] = useState(false);
  const [pipelineCurrentStep, setPipelineCurrentStep] = useState(null); // 'connector', 'pipeline', 'database', 'ai', 'dashboard'

  // Apply theme to body
  useEffect(() => {
    const root = window.document.documentElement;
    if (theme === 'dark') {
      root.classList.add('dark');
      root.style.backgroundColor = '#030303';
    } else {
      root.classList.remove('dark');
      root.style.backgroundColor = '#f4f4f5';
    }
  }, [theme]);

  // Fetch user profile from database with proactive client-side upsert fallback
  const fetchProfile = async (userId, userAuthData) => {
    setProfileLoading(true);
    try {
      let { data, error } = await supabase
        .from('profiles')
        .select('*')
        .eq('id', userId)
        .single();

      if (error && error.code === 'PGRST116') {
        // Single row not found (lag in db triggers or fresh signup) -> Upsert profile
        const newProfile = {
          id: userId,
          full_name: userAuthData.user_metadata?.name || userAuthData.user_metadata?.full_name || '',
          email: userAuthData.email || '',
          phone_number: userAuthData.phone || '',
          profile_photo: userAuthData.user_metadata?.avatar_url || '',
          login_provider: userAuthData.app_metadata?.provider || 'phone',
          last_login: new Date().toISOString(),
          onboarded: false
        };

        const { data: upsertData, error: upsertError } = await supabase
          .from('profiles')
          .upsert(newProfile)
          .select('*')
          .single();

        if (upsertError) throw upsertError;
        data = upsertData;
      } else if (error) {
        throw error;
      }

      setProfile(data);
    } catch (err) {
      console.error('Error fetching user profile:', err);
    } finally {
      setProfileLoading(false);
    }
  };

  // Listen for Supabase Authentication status changes
  useEffect(() => {
    // Initial check
    supabase.auth.getSession().then(({ data: { session } }) => {
      const activeUser = session?.user ?? null;
      setUser(activeUser);
      if (activeUser) {
        fetchProfile(activeUser.id, activeUser);
      } else {
        setProfileLoading(false);
      }
    });

    const { data: { subscription } } = supabase.auth.onAuthStateChange(async (_event, session) => {
      const activeUser = session?.user ?? null;
      setUser(activeUser);
      if (activeUser) {
        await fetchProfile(activeUser.id, activeUser);
      } else {
        setProfile(null);
        setProfileLoading(false);
      }
    });

    return () => subscription.unsubscribe();
  }, []);

  const logout = async () => {
    setProfile(null);
    setProfileLoading(true);
    await supabase.auth.signOut();
    addNotification('Signed out from workspace session', 'system');
  };

  // Toggle Theme helper
  const toggleTheme = () => setTheme(prev => prev === 'dark' ? 'light' : 'dark');

  // Switch Business Helper
  const selectBusiness = (businessId) => {
    setCurrentBusinessId(businessId);
    // Add a notification when switching profiles
    const businessName = BUSINESS_PROFILES.find(b => b.id === businessId)?.name || 'Business';
    addNotification(`Switched context to ${businessName}`, 'system');
  };

  // Add Notification helper
  const addNotification = (text, type = 'system') => {
    const newNotif = {
      id: `n-${Date.now()}`,
      text,
      time: 'Just now',
      type,
      unread: true
    };
    setNotifications(prev => [newNotif, ...prev]);
  };

  // Update specific fields in data (for simulation actions)
  const updateActiveBusinessData = (updater) => {
    setBusinessData(prev => {
      const updatedBusiness = updater(prev[currentBusinessId]);
      return {
        ...prev,
        [currentBusinessId]: updatedBusiness
      };
    });
  };

  // Complete Suggested Action helper
  const completeAction = (actionId) => {
    updateActiveBusinessData(current => ({
      ...current,
      suggestedActions: current.suggestedActions.filter(a => a.id !== actionId)
    }));
    addNotification('AI suggestion action completed successfully', 'success');
  };

  // Handle Suggested Reply Action
  const sendSuggestedReply = (conversationId, replyContent) => {
    updateActiveBusinessData(current => {
      const updatedConvs = current.conversations.map(c => {
        if (c.id === conversationId) {
          return {
            ...c,
            unread: false,
            priority: 'completed',
            snippet: replyContent,
            messages: [
              ...c.messages,
              { id: `m-reply-${Date.now()}`, sender: 'agent', content: replyContent, time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) }
            ]
          };
        }
        return c;
      });

      // Update lead details or sentiment if needed
      const targetConv = current.conversations.find(c => c.id === conversationId);
      const updatedCustomers = current.customers.map(cust => {
        if (cust.id === targetConv.customerId) {
          return {
            ...cust,
            buyingIntent: Math.min(100, cust.buyingIntent + 3),
            timeline: [
              { time: 'Just now', type: 'message_sent', content: 'Sent reply: ' + replyContent.substring(0, 30) + '...' },
              ...cust.timeline
            ]
          };
        }
        return cust;
      });

      return {
        ...current,
        conversations: updatedConvs,
        customers: updatedCustomers
      };
    });
    addNotification('AI response reply sent to customer', 'success');
  };

  // Trigger Google Review reply simulation
  const replyToGoogleReview = (reviewId, replyText) => {
    updateActiveBusinessData(current => {
      const updatedReviews = current.reviews.map(r => {
        if (r.id === reviewId) {
          return { ...r, replied: true, replyText };
        }
        return r;
      });
      return {
        ...current,
        reviews: updatedReviews
      };
    });
    addNotification('Google Review response published', 'success');
  };

  // Simulated Webhook Stream - customer initiates event
  const simulateIncomingWebhook = (channel, customerName, messageText) => {
    if (isPipelineActive) return; // Prevent concurrent simulations
    setIsPipelineActive(true);
    setPipelineLogs([]);

    const log = (step, status, msg) => {
      setPipelineLogs(prev => [
        ...prev,
        { id: Date.now() + Math.random(), step, status, message: msg, timestamp: new Date().toLocaleTimeString() }
      ]);
    };

    // Step 1: Connector Receives Webhook
    setPipelineCurrentStep('connector');
    log('connector', 'active', `Incoming webhook from ${channel.toUpperCase()} webhook API...`);

    setTimeout(() => {
      // Step 2: Data Normalization Pipeline
      setPipelineCurrentStep('pipeline');
      log('pipeline', 'active', `Parsing payload. Normalizing message formats, stripping HTML, deduplicating IDs.`);

      setTimeout(() => {
        log('pipeline', 'active', `Matched payload metadata. Identifying customer footprint for: "${customerName}".`);

        setTimeout(() => {
          // Step 3: Unified Customer DB check & merge
          setPipelineCurrentStep('database');
          log('database', 'active', `Querying Unified Customer Database. Customer record found. Merging conversation thread.`);

          setTimeout(() => {
            // Step 4: AI Engine parses insights
            setPipelineCurrentStep('ai');
            log('ai', 'active', `Running AI NLP Core. Intent detected: "Purchase Inquiry". Sentiment: "Positive (0.88)".`);

            setTimeout(() => {
              log('ai', 'active', `Recalculated Lead Buying Intent: 94%. Flagged priority label: "HOT LEAD".`);
              log('ai', 'active', `AI generated context-aware Suggested Reply Draft.`);

              setTimeout(() => {
                // Step 5: Update Business Command Center
                setPipelineCurrentStep('dashboard');
                log('dashboard', 'active', `Injecting active event block into Unified Inbox stream. Dispatching dashboard updates.`);

                // Update actual react state to show the message live
                updateActiveBusinessData(current => {
                  // Add a new conversation or append to existing one
                  const existingConv = current.conversations.find(c => c.customerName === customerName);

                  let updatedConvs;
                  if (existingConv) {
                    updatedConvs = current.conversations.map(c => {
                      if (c.id === existingConv.id) {
                        return {
                          ...c,
                          unread: true,
                          priority: 'high',
                          snippet: messageText,
                          lastMsgTime: 'Just now',
                          messages: [
                            ...c.messages,
                            { id: `m-sim-${Date.now()}`, sender: 'customer', content: messageText, time: 'Just now' }
                          ]
                        };
                      }
                      return c;
                    });
                  } else {
                    const newCustId = `cust-sim-${Date.now()}`;
                    const newConvId = `conv-sim-${Date.now()}`;
                    
                    const newCustomer = {
                      id: newCustId,
                      name: customerName,
                      avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&q=80&w=120',
                      email: `${customerName.toLowerCase().replace(' ', '.')}@gmail.com`,
                      phone: '+91 99900 88811',
                      leadScore: 88,
                      buyingIntent: 91,
                      sentiment: 'positive',
                      revenue: '₹0',
                      productsViewed: ['Specialty Roast', 'Brunch Menu'],
                      ordersCount: 0,
                      orders: [],
                      aiSummary: 'New lead from simulated webhook. Seeking immediate pricing and availability confirmation.',
                      notes: 'Simulation customer.',
                      timeline: [{ time: 'Just now', type: 'message_received', channel, content: messageText }]
                    };

                    const newConv = {
                      id: newConvId,
                      customerId: newCustId,
                      customerName: customerName,
                      avatar: newCustomer.avatar,
                      channel,
                      unread: true,
                      priority: 'high',
                      intent: 'Pricing Inquiry',
                      sentiment: 'positive',
                      snippet: messageText,
                      lastMsgTime: 'Just now',
                      aiSuggestedReply: `Hi ${customerName}! Thank you for reaching out via ${channel}. We\'d love to help you with that! Yes, we have availability and custom packages for you. Would you like to book?`,
                      messages: [{ id: 'm-sim-1', sender: 'customer', content: messageText, time: 'Just now' }]
                    };

                    current.customers.unshift(newCustomer);
                    current.conversations.unshift(newConv);
                    updatedConvs = [...current.conversations];
                  }

                  // Update metrics
                  return {
                    ...current,
                    unreadMessages: current.unreadMessages + 1,
                    pendingLeads: current.pendingLeads + 1,
                    conversations: updatedConvs,
                    aiSummary: {
                      ...current.aiSummary,
                      enquiries: current.aiSummary.enquiries + 1,
                      hotLeads: current.aiSummary.hotLeads + 1
                    }
                  };
                });

                // Add notification
                addNotification(`Hot Lead Alert: ${customerName} sent a message via ${channel.toUpperCase()}`, 'lead');

                setTimeout(() => {
                  setPipelineCurrentStep(null);
                  setIsPipelineActive(false);
                  log('idle', 'success', `Simulation successfully completed! Command Center dashboard is up to date.`);
                }, 1500);

              }, 1000);
            }, 1000);
          }, 1000);
        }, 1000);
      }, 1000);
    }, 1000);
  };

  const activeBusiness = BUSINESS_PROFILES.find(b => b.id === currentBusinessId) || BUSINESS_PROFILES[0];
  const activeBusinessData = businessData[currentBusinessId];

  return (
    <AppContext.Provider value={{
      theme,
      toggleTheme,
      isLandingPage,
      setIsLandingPage,
      user,
      profile,
      setProfile,
      profileLoading,
      logout,
      currentBusinessId,
      selectBusiness,
      activeBusiness,
      activeBusinessData,
      businessData,
      activeTab,
      setActiveTab,
      notifications,
      addNotification,
      completeAction,
      sendSuggestedReply,
      replyToGoogleReview,
      searchQuery,
      setSearchQuery,
      integrations,
      setIntegrations,
      // Pipeline
      simulateIncomingWebhook,
      pipelineLogs,
      isPipelineActive,
      pipelineCurrentStep
    }}>
      {children}
    </AppContext.Provider>
  );
}

export function useApp() {
  return useContext(AppContext);
}
